version: '3'

services:
  gs:
    build: .
    command: "mix run --no-halt"
    environment:
      - MIX_ENV=prod
      - STORAGE_URL=redis://redis:6379/0
      - HOSTNAME=localhost
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 10000:10000
    links:
      - redis

  redis:
    image: redis
